### ISSUE TITLE
Support data path translation for pipeline access

### ISSUE THREAD

**Issue by marxide** [askap-vast/vast-tools#278]
Now that the VAST-P1 paper has been submitted, we wish to move onto analysis of the full VAST dataset using the latest pipeline version. We don't want to simply replace the existing pipeline with the new version since the existing pipeline runs have been used for publications and we may need to access it in future. Instead, we'd like to serve both the existing VAST-P1 pipeline instance and a new instance that uses the latest pipeline and corrected survey data.

To achieve this, I have been working on cleaning up the infrastructure of our Nimbus deployments. I've settled on supporting running our various services (e.g. the pipeline, JupyterHub, metadata, etc) in containers to simplify their management. One of the main advantages to this approach is that we can create multiple instances of these services on the same Nimbus VM while keeping them isolated and portable, which addresses the problem outlined above.

However, this containerised approach introduces a new problem: the `vast-tools` pipeline module assumes it is being run on the same system as the pipeline which is not true for containers. The containers may be running on the same physical system, but they are isolated from the perspective of the processes running within the containers. Currently, `vast-tools.pipeline.Pipeline` allows the user to change where it looks for the pipeline runs using the `project_dir` kwarg, but again this assumes that the data paths the pipeline used will be the same on the Jupyter server.

In order for `vast-tools` to access pipeline runs and their associated data, the single-user Jupyter servers spawned by JupyterHub will need to access the pipeline working directory (runs), raw image directory (survey data), and the home data directory (additional data that may have been provided by a user). These paths are defined in the pipeline .env file as `PIPELINE_WORKING_DIR`, `RAW_IMAGE_DIR`, and `HOME_DATA_ROOT/<username>/HOME_DATA_DIR`, respectively. These directories must be accessible to the spawned single-user Jupyter servers, but since the paths could clash between pipeline instances, the mount/bind points should be unique and not necessarily the same as the originals. Therefore, some user-defined translations of the data file paths is required.

To illustrate the problem, consider that we have 3 pipeline instances: a v0.2.0, v1.0.0, and v1.1.0 instance. All of these instances contain several runs and users wish to access runs from all instances for analysis on JupyterHub using `vast-tools`.

The instances were configured with the following data path settings:

```
# v0.2.0
PIPELINE_WORKING_DIR=/mnt/pipeline-runs/runs
RAW_IMAGE_DIR=/data/pilot
# note that the home data feature was not implemented for this version

# v1.0.0
PIPELINE_WORKING_DIR=/data/vast-pipeline/vast-pipeline/pipeline-runs
RAW_IMAGE_DIR=/data/vast-survey/pilot_corrected_racs_cres
HOME_DATA_DIR=vast-pipeline-extra-data
HOME_DATA_ROOT=/data/vast-user-home-data

# v1.1.0
PIPELINE_WORKING_DIR=/data/vast-pipeline/vast-pipeline/pipeline-runs
RAW_IMAGE_DIR=/data/vast-survey/pilot_corrected_racs_cres
HOME_DATA_DIR=vast-pipeline-extra-data
HOME_DATA_ROOT=/data/vast-user-home-data
```

Note that since the pipeline can be run in a container, the data paths are arbitrary. For example, the data paths for the v1.0.0 and v1.1.0 instances above are exactly the same, but this doesn't mean they point to the same physical files as they could be mounted from different sources.

If we want the Jupyter servers to be able to access runs from all of these pipeline instances, the above data paths must be mounted to the single-user Jupyter servers. I can see two ways to do this:

1. Bind all configured data paths _to the same location_. e.g. `/mnt/pipeline-runs/runs` from the v0.2.0 instance is bound to `/mnt/pipeline-runs/runs` on the single-user Jupyter servers. This simple approach will work only if the instances have unique data paths, which in this example is not true.

2. Bind all configured data paths _to arbitrary unique locations_. e.g. `/mnt/pipeline-runs/runs` from the v0.2.0 instance is bound to `/data/pipeline-v0.2.0/runs` on the single-user Jupyter servers. Since each bind target may now be unique, clashes between the v1.0.0 and v1.1.0 paths are avoided. However, `vast-tools` will now fail to find some files as it retrieves some data paths from the parquet files which contain the original absolute data paths from the pipeline instance. For example, the measurements are read from the measurement parquets which are located using the paths stored in the images parquet, which are absolute paths on the pipeline instance, not the Jupyter server instance.

The latter option is more flexible but requires changes to `vast-tools` to translate the original data paths to the new bind targets.

My proposed solution is to add a `data_paths: Dict[str, str]` kwarg to `Pipeline.__init__` (open to renaming suggestions) that is used to translate the data paths on-the-fly when accessing the data. Continuing the example from above, a `Pipeline` object could be created for the v0.2.0 instance with:

```python
from vasttools.pipeline import Pipeline

pipeline_v020 = Pipeline(
    project_dir="/data/pipeline-v0.2.0/runs",
    data_paths={
        "/mnt/pipeline-runs/runs": "/data/pipeline-v0.2.0/runs",
        "/data/pilot": "/data/pipeline-v0.2.0/survey-data",
    }
)
```

Whenever a path that begins with `/mnt/pipeline-runs/run` or `/data/pilot`, it will be translated to `/data/pipeline-v0.2.0/runs` and `/data/pipeline-v0.2.0/survey-data` respectively. We may also want to add another environment variable, similar to `VAST_DATA_DIR` and `PIPELINE_WORKING_DIR`, that could act as a default in case no kwargs are passed to `Pipeline.__init__`. We would also publish the data path mappings on the wiki so users can look up the required paths for each available pipeline instance.

Anyone more familiar with `vast-tools` see a problem with this approach?

**Comment by ajstewart** [comment]
Closing this issue as it was decided to solve it using JupiterHub because of the versioning requirements. Please reopen @marxide if this is not the case.
