### ISSUE TITLE
Query breaks if called directly from a script

### ISSUE THREAD

**Issue by ddobie** [askap-vast/vast-tools#316]
The dask multiprocessing inside `find_fields` (and presumably elsewhere) will throw a RuntimeError if called directly from a script.

The solution is relatively simple (see [here](https://github.com/dask/distributed/issues/2520)) but the error is incredibly hard to pin down if you don't know what you're looking for.

I don't think there's a straightforward way to get around this, but we should at least throw an error before `find_fields` is called (ideally when Query is initialised) that is more straightforward to interpret.

**Comment by ajstewart** [comment]
I don't think there is much to do with this apart from making it clear in the documentation that this needs to be done.
