### ISSUE TITLE
Enable access to Tiles RMS data 

### ISSUE THREAD

**Issue by ddobie** [askap-vast/vast-tools#320]
In the past RMS data didn't exist for TILES and therefore various checks were put into the `Query` class to ensure scripts exited gracefully if RMS tiles data was requested.

However, that data now exists and therefore we should be providing access to it.

To do:
* Update _add_files to calculate the correct rms_file path
* Remove validation statements in Query initialisation

**Comment by ajstewart** [comment]
#217 also had this aim.
