### ISSUE TITLE
Check docs for errors

### ISSUE THREAD

**Issue by ddobie** [askap-vast/vast-tools#352]
There have been a number of large changes since the latest release. This probably warrants having a look through the docs for typos, errors etc.

**Comment by ajstewart** [comment]
You reckon that epoch 12 warning could be removed as part of this? Both in the docs and the code? I noticed it when experimenting with something the other day, thought it probably wasn't worth carrying forward (maybe).

**Comment by ddobie** [comment]
Yes I think you're probably right. It's been in-place for probably 9-12 months now so I can't imagine there's anyone using the old definitions.
